### PR TITLE
Added fedora/redhat build script

### PR DESCRIPTION
**Pull request by evilsephiroth**
Just a simple duplicate script to handle fedora/redhat distribution.

Built qemu correctly on Fedora 28

### CODE REVIEW

**Comment by saveriomiroddi** [comment]
Hello! I'm on holiday for a couple of weeks :smile: 

I will review once I'm back!

**Comment by evilsephiroth** [comment]
No problem.  Intanto buone vacanze :-)

**Comment by evilsephiroth** [comment]
Added libusbx-devel to allow usb host passthrough

**Comment by saveriomiroddi** [comment]
@evilsephiroth 

Hello! So, I'm about to merge the PR.

Due to the repository structure policy (branches, including master, have only two commits on top of the upstream tag, one with the documentation+build script, and the other with the patch), I will need to squash your commit, so your contributions count may or may not increase (just in case you're into commit counting :wink:).

After the merge, I'm creating a PR with an improvement, I will ask your help for testing :smile: 

ps. ciao!!

**Pull request merged**
